sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.4.0
  - 2.4.1
  - 2.5.1
  - 2.6.3
  - jruby
  - truffleruby
before_install:
  - gem install bundler
  - export TZ=Asia/Kolkata
script: bundle exec rspec spec
