source 'https://rubygems.org'
ruby '2.4.0'

gem 'puma'
gem 'pry'
gem 'luis', github: 'tachyons/luis', branch: 'master'
gem 'bot_framework', github: 'tachyons/botframework-ruby', branch: 'master'
gem 'bmtc', github: 'tachyons/bmtc', branch: 'master'
