source 'https://rubygems.org'
ruby '2.4.2'

# gem 'bot_framework', path: '../../../bot_framework'
gem 'bot_framework', github: 'tachyons/botframework-ruby', branch: 'master'
gem 'luis', github: 'tachyons/luis', branch: 'master'
gem 'pry'
gem 'puma'
